terms_by_type = {
    "Additional Liability Company": [
        "tovarystvo z dodatkvoiu vidpovidalnistiu",
        "товариство з додатковою відповідальністю",
    ],
    "Association of Co-Owners": [
        "association des coproprietaires de",
        "associação comunitária dos moradores",
        "společenství vlastníků jednotek",
        "syndicat de la copropriété du",
        "vereniging van mede eigenaars van",
    ],
    "Cooperative Company with Limited Liability": [
        "eingetragene genossenschaft mit beschrankter haftpflicht",
    ],
    "Corporation": [
        "& co",
        "& co.",
        "a.g.",
        "ag",
        "co",
        "co.",
        "company",
        "corp",
        "corp.",
        "corporation",
        "inc",
        "inc.",
        "incorporated",
        "n.v.",
        "nuf",
        "oao",
        "s.a.",
        "s.f.",
        "s.p.a.",
    ],
    "General Partnership": [
        " i/s",
        "a spol.",
        "ans",
        "ay",
        "bt.",
        "d.n.o.",
        "da",
        "hb",
        "j.t.d.",
        "kgaa",
        "ltda.",
        "mb",
        "o.d.",
        "o.e.",
        "oe",
        "og",
        "pt",
        "s.a.p.a.",
        "s.f.",
        "s.n.c.",
        "s.s.",
        "sd",
        "snc",
        "soc.col.",
        "sp.j.",
        "stg",
        "v.o.f.",
        "v.o.s.",
        "veÅ. obch. spol.",
    ],
    "Joint Stock / Unlimited": [
        "a.s.",
        "aj",
        "akc. spol.",
        "akciová společnost",
        "aktiengesellschaft",
        "oaj",
        "sal",
        "saoc",
        "saog",
        "ultd",
        "unlimited",
        "unltd",
        "yoaj",
    ],
    "Joint Venture": [
        "esv",
        "gie",
        "kv.",
        "qk",
    ],
    "Limited": [
        "as",
        "b.v.",
        "bhd.",
        "bvba",
        "d.o.o.",
        "d.o.o.e.l.",
        "ehf.",
        "g.m.b.h",
        "gesellschaft mit beschränkter haftung",
        "gmbh",
        "kft.",
        "kht.",
        "l.t.d.",
        "lda.",
        "limited",
        "ltd",
        "ltda",
        "ood",
        "oy",
        "pp",
        "pty ltd",
        "pty. ltd.",
        "rt.",
        "s. de r.l.",
        "s. de r.l. de c.v.",
        "s.a.r.l.",
        "s.l.",
        "s.l.n.e.",
        "s.r.l.",
        "sdn bhd",
        "sdn. bhd.",
        "sp. z o.o.",
        "sp. z.o.o.",
        "sprl",
        "spółka z o.o.",
        "spółka z ograniczoną odpowiedzialnością",
        "tapui",
        "teo",
        "tov",
        "tovarystvo z obmezhenoiu vidpovidalnistiu",
        "uab",
        "zrt.",
        "товариство з обмеженою відповідальністю",
    ],
    "Limited Liability Company": [
        "3at",
        "a.d.",
        "a.e.",
        "a/s",
        "aat",
        "ab",
        "ae",
        "aps",
        "as",
        "asa",
        "cpt",
        "d.d.",
        "dat",
        "eurl",
        "exploitation agricole à responsabilité limitée",
        "hf.",
        "l.l.c.",
        "llc",
        "mchj",
        "nv",
        "nyrt.",
        "ooo",
        "oyj",
        "p.l.c.",
        "p/s",
        "plc",
        "plc.",
        "pryvatne pidpryyemstvo",
        "s. r. o.",
        "s.a.",
        "s.m.b.a.",
        "s.r.l.",
        "s.r.o.",
        "sa",
        "sabiedrība ar ierobežotu atbildību",
        "sae",
        "sarl",
        "sasu",
        "sh.a.",
        "smba",
        "spol. s r. o.",
        "spol. s r.o.",
        "spol. s.r.o.",
        "společnost s ručením omezeným",
        "spoločnosť s ručením obmedzeným",
        "srl",
        "srl.",
        "vat",
        "zat",
        "приватне підприємство",
    ],
    "Limited Liability Company in Liquidation": [
        "s.r.o. v likvidácii",
        "s.r.o. v likvidácii",
        "spol. s r.o. v likvidaci",
        "spol. s r.o. v likvidácii",
        "spol. s.r.o. v likvidaci",
        "spol. s.r.o. v likvidácii",
        "spółka z ograniczoną odpowiedzialnością likwidacji",
    ],
    "Limited Liability Limited Partnership": [
        "l.l.l.p.",
        "lllp",
    ],
    "Limited Liability Partnership": [
        "l.l.p.",
        "llp",
        "s.c.a.",
        "s.c.s.",
        "sp.p.",
    ],
    "Limited Partnership": [
        "c.v.",
        "comm.v",
        "e.e.",
        "ee",
        "gmbh & co. kg",
        "k.d.",
        "k.d.a.",
        "k.s.",
        "k/s",
        "kb",
        "kd",
        "kda",
        "kg",
        "komanditná spoločnosť",
        "komanditní společnost",
        "kommanditgesellschaft",
        "ks",
        "kt",
        "ky",
        "l.p.",
        "lp",
        "s. en c.",
        "s.a.s.",
        "s.c.p.a",
        "s.c.s.",
        "s.cra.",
        "s.k.a.",
        "scs",
        "secs",
        "sp.k.",
        "spółka komandytowa",
    ],
    "Mutual Fund": [
        "sicav",
    ],
    "No Liability": [
        "nl",
    ],
    "Non-Profit": [
        "gte.",
        "ses.",
        "vzw",
    ],
    "Private Company": [
        "private",
        "pte",
        "xk",
    ],
    "Professional Corporation": [
        "p.c.",
        "vof",
    ],
    "Professional Limited Liability Company": [
        "p.l.l.c.",
        "pllc",
    ],
    "Sole Proprietorship": [
        "e.c.",
        "e.u.",
        "e.v.",
        "et",
        "fie",
        "fop",
        "ij",
        "obrt",
        "s.p.",
        "t:mi",
        "tmi",
        "xt",
    ],
}

terms_by_country = {
    "Albania": [
        "sh.a.",
        "sh.p.k.",
    ],
    "Argentina": [
        "s.a.",
        "s.c.e i.",
        "s.c.p.a",
        "s.e.",
        "s.g.r",
        "s.r.l.",
        "scpa",
        "soc.col.",
    ],
    "Australia": [
        "nl",
        "pty ltd",
        "pty. ltd.",
    ],
    "Austria": [
        "a.g.",
        "ag",
        "e.u.",
        "gesbr",
        "kg",
        "og",
        "stg",
    ],
    "Belarus": [
        "3at",
        "aat",
        "oao",
        "rup",
        "taa",
        "tavarystva z abmezhavanaj adkaznascyu",
        "up",
        "zakrytae akcyyanernae tavarystva",
        "zao",
        "zat",
        "аат",
        "адкрытае акцыянернае таварыства",
        "ва",
        "вытворчае аб'яднанне",
        "дачэрняя кампанія",
        "дп",
        "закрытае акцыянернае таварыства",
        "закрытое акционерное общество",
        "зао",
        "зат",
        "иностранное общество с ограниченной ответственностью",
        "иооо",
        "канцэрн",
        "оао",
        "общество с дополнительной ответственностью",
        "общество с ограниченной ответственностью",
        "одо",
        "ооо",
        "открытое акционерное общество",
        "республиканское унитарное предприятие",
        "руп",
        "совместное общество с ограниченной ответственностью",
        "сооо",
        "таа",
        "таварыства з абмежаванай адказнасцю",
        "таварыства з дадатковай адказнасцю",
        "тда",
        "тк",
        "транснацыяльны канцэрн",
        "унитарное предприятие",
        "унітарнае прадпрыемства",
        "уп",
        "фпг",
        "фінансово-промислова група",
        "холдынг",
        "частное предприятие",
        "частное производственно торговое унитарное предприятие",
        "частное транспортное унитарное предприятие",
        "частное унитарное предприятие",
        "частное унитарное предприятие",
        "чп",
        "чтуп",
        "чуп",
    ],
    "Belgium": [
        "bvba",
        "comm.v",
        "cvba",
        "cvoa",
        "esv",
        "gie",
        "sca",
        "scs",
        "sep",
        "snc",
        "sprl",
        "vof",
        "vzw",
    ],
    "Bosnia / Herzegovina": [
        "a.d.",
        "d.d.",
        "d.n.o.",
        "d.o.o.",
        "k.v.",
        "s.p.",
    ],
    "Brazil": [
        "ad",
        "adsitz",
        "ead",
        "et",
        "kd",
        "kda",
        "ltda",
        "pllc",
        "s.a.",
        "sd",
    ],
    "Bulgaria": [
        "ad",
        "adsits",
        "adsitz",
        "aktsionerno drujestvo",
        "aktsionerno druzhestvo sus spetsialna investitsionna tsel",
        "drujestvo s ogranichena otgovornost",
        "ead",
        "ednolichen turgovetz",
        "ednolichno aktsionerno druzhestvo",
        "ednolichno druzhestvo s ogranichena otgovornost",
        "eood",
        "et",
        "et",
        "kd",
        "kd",
        "kda",
        "kda",
        "komanditno druzhestvo",
        "komanditno druzhestvo s aktzii",
        "ood",
        "sd",
        "sd",
        "subiratelno druzhestvo",
        "ад",
        "адсиц",
        "акционерно дружество",
        "акционерно дружество със специална инвестиционна цел",
        "дружество с ограничена отговорност",
        "еад",
        "едноличен търговец",
        "едноличен търговец",
        "еднолично акционерно дружество",
        "еднолично дружество с ограничена отговорност",
        "еоод",
        "ет",
        "кд",
        "кда",
        "командитно дружество",
        "командитно дружество с акции",
        "оод",
        "сд",
        "събирателно дружество",
        "частное торговое унитарное предприятие",
    ],
    "Cambodia": [
        "gp",
        "peec",
        "plc ltd.",
        "pte ltd.",
        "sm pte ltd.",
        "sp",
    ],
    "Canada": [
        "gp",
        "lp",
        "sp",
    ],
    "Chile": [
        "eirl",
        "ltda",
        "ltda.",
        "s. en c.",
        "s.a.",
        "s.g.r.",
        "s.p.a.",
        "sa",
        "sgr",
    ],
    "China": [
        "gǔfèn yǒuxiàn gōngsī)",
        "wúxiàn zérèn gōngsī",
        "yǒuxiàn gōngsī",
        "yǒuxiàn zérèn gǔfèn gōngsī",
        "上市公司",
        "公司集团",
        "公司集團",
        "担保有限公司",
        "擔保有限公司",
        "无限责任公司",
        "有限公司",
        "有限公司",
        "有限合伙",
        "有限合夥",
        "有限責任公司",
        "有限責任股份公司",
        "有限责任",
        "有限责任公司",
        "有限责任股份公司",
        "無限責任公司",
        "私人公司",
        "股份公司",
        "股份有限公司",
        "集团公司",
        "集團公司",
    ],
    "Columbia": [
        "e.u.",
        "s.a.",
        "s.a.s.",
        "sca",
        "suc. de descendants",
    ],
    "Croatia": [
        "d.d.",
        "d.o.o.",
        "obrt",
    ],
    "Czech Republic": [
        "a spol.",
        "a.s.",
        "akc. spol.",
        "k.s.",
        "kom. spol.",
        "s.r.o.",
        "spol. s r. o.",
        "spol. s r.o.",
        "v.o.s.",
        "veÅ. obch. spol.",
    ],
    "Denmark": [
        "a.m.b.a.",
        "a/s",
        "amba",
        "f.m.b.a.",
        "fmba",
        "g/s",
        "i/s",
        "k/s",
        "p/s",
        "s.m.b.a.",
        "smba",
    ],
    "Dominican Republic": [
        "c. por a.",
        "cxa",
        "eirl.",
        "s.a.",
        "s.a.s.",
        "sa",
        "sas",
        "srl",
        "srl.",
    ],
    "Ecuador": [
        "c.a.",
        "ep",
        "s.a.",
        "sa",
    ],
    "Egypt": [
        "sae",
    ],
    "Estonia": [
        "as",
        "fie",
        "oü",
    ],
    "Finland": [
        "as oy",
        "as.oy",
        "ay",
        "ky",
        "ok",
        "oy",
        "oyj",
        "t:mi",
        "tmi",
    ],
    "France": [
        "ei",
        "eurl",
        "fcp",
        "gie",
        "sarl",
        "sas",
        "sasu",
        "sca",
        "sci",
        "scop",
        "scs",
        "sem",
        "sep",
        "sicav",
        "snc",
        "societe civile immobiliere",
        "sogepa",
    ],
    "Germany": [
        "ag",
        "aktiengesellschaft",
        "e.g.",
        "e.v.",
        "egmbh",
        "eingetragene genossenschaft mit beschränkter haftpflicht",
        "g.m.b.h.",
        "gbr",
        "gesellschaft mit beschränkter haftung",
        "gmbh",
        "gmbh & co. kg",
        "kg",
        "kgaa",
        "kommanditgesellschaft",
        "mbh & co. kg",
        "ohg",
        "partg",
    ],
    "Greece": [
        "Anónimi Etaireía",
        "Anónimi Viomichanikí Emborikí Etaireía",
        "Etaireía Periorisménis Efthínis",
        "Eterórrithmi Etaireía",
        "I.K.E.",
        "Idiotiki Kefalaiouchiki Etaireía",
        "Monoprósopi Etaireía Periorisménis Efthínis",
        "Omórrithmi Etaireía",
        "Omórrithmi Viomichanikí Emborikí Etaireía",
        "a.e.",
        "ae",
        "atomikís epicheírisis",
        "e.e.",
        "e.p.e.",
        "ee",
        "epe",
        "m.e.p.e.",
        "mepe",
        "o.e.",
        "o.v.e.e.",
        "oe",
        "ovee",
        "Ανώνυμη Βιομηχανική Εμπορική Εταιρεία",
        "Ανώνυμη Εταιρεία",
        "Ε.Π.Ε.",
        "Εταιρεία Περιορισμένης Ευθύνης",
        "Ετερόρρυθμη Εταιρία",
        "Ιδιωτική Κεφαλαιουχική Εταιρεία",
        "Μ.Ε.Π.Ε.",
        "Μονοπρόσωπη Ε.Π.Ε.",
        "Ο.Β.Ε.Ε.",
        "Ο.Ε.",
        "Ομόρρυθμη Βιομηχανική Εμπορική Εταιρεία",
        "Ομόρρυθμη Εταιρεία",
        "ατομικής επιχείρησης",
    ],
    "Guatemala": [
        "s.a.",
        "sa",
    ],
    "Haiti": [
        "sa",
    ],
    "Hong Kong": [
        "limited",
        "ltd",
        "ultd",
        "unltd",
    ],
    "Hungary": [
        "bt.",
        "e.c.",
        "e.v.",
        "ec",
        "ev",
        "k.v.",
        "kft.",
        "kht.",
        "kkt.",
        "nyrt",
        "rt.",
        "zrt.",
    ],
    "Iceland": [
        "ehf.",
        "hf.",
        "ohf.",
        "s.f.",
        "ses.",
    ],
    "India": [
        "ltd.",
        "pse",
        "psu",
        "pvt. ltd.",
    ],
    "Indonesia": [
        "fa",
        "pt",
        "ud",
    ],
    "Ireland": [
        "cpt",
        "teo",
    ],
    "Israel": [
        "b.m.",
        "bm",
        "limited",
        "ltd",
    ],
    "Italy": [
        "s.a.p.a.",
        "s.a.s.",
        "s.c.r.l.",
        "s.n.c.",
        "s.p.a.",
        "s.r.l.",
        "s.s.",
    ],
    "Japan": [
        "g.k.",
        "gk",
        "k.k.",
        "y.k.",
    ],
    "Latvia": [
        "as",
        "ik",
        "ks",
        "ps",
        "sia",
    ],
    "Lebanon": [
        "sal",
    ],
    "Lithuania": [
        "ab",
        "ij",
        "mb",
        "uab",
    ],
    "Luxembourg": [
        "s.a.",
        "s.a.r.l.",
        "secs",
    ],
    "Macedonia": [
        "a.d.",
        "d.o.o.",
        "d.o.o.e.l",
        "j.t.d.",
        "k.d.",
        "k.d.a.",
    ],
    "Malaysia": [
        "bhd.",
        "sdn bhd",
        "sdn. bhd.",
    ],
    "Mexico": [
        "s. de. r.l.",
        "s. en c.",
        "s.a.",
        "s.a. de c.v.",
        "s.a.b.",
        "s.a.p.i.",
    ],
    "Moldova": [
        "societatea cu raspundere limitata",
    ],
    "Mongolia": [
        "xk",
        "xxk",
    ],
    "Montenegro": [
        "A.D.",
        "Akcionarsko Društvo",
        "D.O.O.",
        "Društvo sa Ograničenom Odgovornošću",
        "K.D.",
        "Komanditno Društvo",
        "O.D.",
        "Ortačko Društvo",
        "Preduzetnik",
    ],
    "Netherlands": [
        "b.v.",
        "c.v.",
        "n.v.",
        "stichting",
        "v.o.f.",
    ],
    "New Zealand": [
        "limited",
        "ltd",
        "tapui",
    ],
    "Nigeria": [
        "gte.",
        "ltd.",
        "plc",
        "ultd.",
    ],
    "Norway": [
        "ans",
        "as",
        "asa",
        "ba",
        "bl",
        "da",
        "etat",
        "fkf",
        "hf",
        "iks",
        "kf",
        "ks",
        "nuf",
        "rhf",
        "sf",
    ],
    "Oman": [
        "saoc",
        "saog",
    ],
    "Pakistan": [
        "limited",
        "ltd",
        "ltd.",
        "pvt. ltd.",
    ],
    "Peru": [
        "s.a.",
        "s.a.a.",
        "sa",
    ],
    "Philippines": [
        "coop.",
        "corp",
        "corp.",
        "ent.",
        "inc",
        "inc.",
        "l.l.c.",
        "llc",
        "ltd.",
    ],
    "Poland": [
        "p.p.",
        "s.a.",
        "s.c.",
        "s.k.a.",
        "sp. z.o.o.",
        "sp.j.",
        "sp.k.",
        "sp.p.",
        "spółka z ograniczoną odpowiedzialnością",
    ],
    "Portugal": [
        "crl",
        "lda.",
        "s.a.",
        "s.f.",
        "sgps",
    ],
    "Romania": [
        "o.n.g.",
        "organizație non-guvernamentală",
        "persoana fizica autorizata",
        "pfa",
        "s.a.",
        "s.c.a.",
        "s.c.s.",
        "s.n.c.",
        "s.r.l.",
        "societate cu răspundere limitată",
        "societatea cu răspundere limitată cu proprietar unic",
        "societatea pe acțiuni",
        "societatea în comandită pe acțiuni",
        "societatea în comandită simplă",
        "societatea în nume colectiv",
        "societăți de persoane",
        "srl cu proprietar unic",
        "întreprindere individuală",
        "întreprinderea individuală",
    ],
    "Russia": [
        "3ao",
        "akcionernoe obshhestvo",
        "ao",
        "fgup",
        "fkp",
        "gk",
        "gruppa kompanij",
        "kao",
        "oao",
        "ooo",
        "pao",
        "zakrytoe akcionernoe obshhestvo",
        "zao",
        "zao",
        "автономная некоммерческая организация",
        "акционерное общество",
        "ано",
        "ао",
        "артель",
        "благотворительное учреждение",
        "благотворительный фонд",
        "бф",
        "ган",
        "гау",
        "гбу",
        "гк",
        "гку",
        "государственная академия наук",
        "государственная компания",
        "государственная корпорация",
        "государственное автономное учреждение",
        "государственное бюджетное учреждение",
        "государственное казенное учреждение",
        "государственное унитарное предприятие",
        "группа компаний",
        "гупс",
        "закрытое акционерное общество",
        "зао",
        "индивидуальный предприниматель",
        "интегрированная структура",
        "ип",
        "казенное предприятие",
        "колхоз",
        "коммандитное товарищество",
        "кооперативное хозяйство",
        "коопхоз",
        "кп",
        "крестьянское хозяйство",
        "кх",
        "мау",
        "мбу",
        "межправительственная международная организация",
        "мкп",
        "мку",
        "ммо",
        "муниципальное автономное учреждение",
        "муниципальное бюджетное учреждение",
        "муниципальное казенное предприятие",
        "муниципальное казенное учреждение",
        "муниципальное унитарное предприятие",
        "муп",
        "негосударственный пенсионный фонд",
        "неправительственная международная организация",
        "нмо",
        "нпф",
        "оао",
        "оао",
        "общественное учреждение",
        "общественный фонд",
        "общество с ограниченной ответственностью",
        "оинно",
        "ооо",
        "ооо",
        "отделение иностранной некоммерческой неправительственной организации",
        "открытое акционерное общество",
        "оу",
        "оф",
        "пао",
        "пао",
        "пк",
        "полное товарищество",
        "ппк",
        "производственный кооператив",
        "пт",
        "публично-правовая компания",
        "публичное акционерное общество",
        "ра",
        "ран",
        "религиозная организация",
        "ро",
        "российская академия наук",
        "рыболовецкая артель",
        "са",
        "сельскохозяйственная артель",
        "сельскохозяйственный производственный кооператив",
        "спк",
        "товарищество на вере",
        "унитарное предприятие",
        "уп",
        "учреждение",
        "фгау",
        "фгбу",
        "фгку",
        "фгуп",
        "федеральное государственное автономное учреждение",
        "федеральное государственное бюджетное учреждение",
        "федеральное государственное казенное учреждение",
        "федеральное государственное унитарное предприятие",
        "федеральное казенное предприятие",
        "фермерское хозяйство",
        "фкп",
        "фонд",
        "фх",
        "хк",
        "хо",
        "хозяйственное общество",
        "хозяйственное партнерство",
        "хозяйственное товарищество",
        "холдинговая компания",
        "хп",
        "хт",
        "частное учреждение",
        "чу",
        "экологический фонд",
        "эф",
    ],
    "Serbia": [
        "a.d.",
        "d.o.o.",
        "k.d.",
        "o.d.",
    ],
    "Singapore": [
        "bhd",
        "l.l.p.",
        "llp",
        "ltd.",
        "pte",
        "pte ltd",
        "pte. ltd.",
        "sdn bhd",
    ],
    "Slovakia": [
        "a spol.",
        "a.s.",
        "akc. spol.",
        "k.s.",
        "kom. spol.",
        "s.r.o.",
        "spol. s r. o.",
        "spol. s r.o.",
        "v.o.s.",
    ],
    "Slovenia": [
        "d.d.",
        "d.n.o.",
        "d.o.o.",
        "k.d.",
        "s.p.",
    ],
    "Spain": [
        "s.a.",
        "s.a.d.",
        "s.c.",
        "s.coop",
        "s.cra",
        "s.l.",
        "s.l.l.",
        "s.l.n.e.",
        "sal",
        "sccl",
    ],
    "Sweden": [
        "ab",
        "hb",
        "kb",
    ],
    "Switzerland": [
        "ab",
        "g.m.b.h.",
        "gmbh",
        "sa",
        "sagl",
        "sarl",
    ],
    "Turkey": [
        "koop.",
    ],
    "Ukraine": [
        "aktsionerne tovarystvo",
        "at",
        "at",
        "dat",
        "derzhavne aktsionerne tovarystvo",
        "dochp",
        "dp",
        "fizychna osoba pidpryyemets",
        "fop",
        "ip",
        "komandytne tovarystvo",
        "kt",
        "mpp",
        "pat",
        "povne tovarystvo",
        "pp",
        "prat",
        "prytvatne aktsionerne tovarystvo",
        "pryvatne pidpryyemstvo",
        "pt",
        "publichne aktsionerne tovarystvo",
        "pzii",
        "sp",
        "tdv",
        "tob",
        "tov",
        "vat",
        "vidkryte aktsionerne tovarystvo",
        "zakryte aktsionerne tovarystvo",
        "zat",
        "аб",
        "акціонерне товариство",
        "ао",
        "ат",
        "ат",
        "бо",
        "вiдкрите акцiонерне товариство",
        "ват",
        "ват",
        "вк",
        "вкксу",
        "гк",
        "го",
        "громадська організація",
        "гс",
        "даз",
        "дат",
        "державне акціонерне товариство",
        "до",
        "дочп",
        "дп",
        "жбк",
        "закрите акцiонерне товариство",
        "зат",
        "зат",
        "зіі",
        "кб",
        "ко",
        "командитне товариство",
        "кп",
        "кс",
        "кт",
        "кт",
        "мпп",
        "нпф",
        "оас",
        "одв",
        "ок",
        "омс",
        "оо",
        "оог",
        "оп",
        "ор",
        "осбб",
        "осн",
        "осс",
        "пt",
        "пат",
        "пат",
        "пзіі",
        "по",
        "повне товариство",
        "пог",
        "пп",
        "пп",
        "прат",
        "прат",
        "приватне акціонерне товариство",
        "приватне підприємство",
        "пск",
        "пт",
        "публічне акціонерне товариство",
        "пфо",
        "піі",
        "релігійна організація",
        "ро",
        "свк",
        "ск",
        "сок",
        "сп",
        "сп у формі тов",
        "спд",
        "сс",
        "сст",
        "ст",
        "тб",
        "тдв",
        "тдв",
        "тзов",
        "тов",
        "тс",
        "фб",
        "фг",
        "фоп",
        "фоп",
        "фізична особа підприємець",
        "хк",
        "іп",
    ],
    "United Kingdom": [
        "cic",
        "cio",
        "l.l.p.",
        "l.p.",
        "limited",
        "llp",
        "lp",
        "ltd",
        "ltd.",
        "plc",
        "plc.",
    ],
    "United States of America": [
        "& co",
        "& co.",
        "& company",
        "and company",
        "co",
        "co.",
        "company",
        "corp",
        "corp.",
        "corporation",
        "inc",
        "inc.",
        "incorporated",
        "l.l.p.",
        "limited",
        "llc",
        "llp",
        "lp",
        "ltd",
        "ltd.",
        "pllc",
    ],
    "Uzbekistan": [
        "aj",
        "mchj",
        "oaj",
        "ok",
        "qk",
        "qmj",
        "uk",
        "xk",
        "xt",
        "yoaj",
    ],
}
