terms_by_type = {
    "Additional Liability Company": [
        "товариство з додатковою відповідальністю",
        "tovarystvo z dodatkvoiu vidpovidalnistiu",
    ],
    "Assocation of Co-Owners": [
        "vereniging van mede eigenaars van",
        "association des coproprietaires de",
        "společenství vlastníků jednotek",
        "syndicat de la copropriété du",
        "associação comunitária dos moradores",
    ],
    "Cooperative Company with Limited Liability": [
        "eingetragene genossenschaft mit beschrankter haftpflicht",
    ],
    "Corporation": [
        "company",
        "incorporated",
        "corporation",
        "corp.",
        "corp",
        "inc",
        "& co.",
        "& co",
        "inc.",
        "s.p.a.",
        "n.v.",
        "a.g.",
        "ag",
        "nuf",
        "s.a.",
        "s.f.",
        "oao",
        "co.",
        "co",
    ],
    "General Partnership": [
        "soc.col.",
        "stg",
        "d.n.o.",
        "ltda.",
        "v.o.s.",
        "a spol.",
        "ve\xc5\x99. obch. spol.",
        "kgaa",
        "o.e.",
        "s.f.",
        "s.n.c.",
        "s.a.p.a.",
        "j.t.d.",
        "v.o.f.",
        "sp.j.",
        "og",
        "sd",
        " i/s",
        "ay",
        "snc",
        "oe",
        "bt.",
        "s.s.",
        "mb",
        "ans",
        "da",
        "o.d.",
        "hb",
        "pt",
    ],
    "Joint Stock / Unlimited": [
        "unltd",
        "ultd",
        "sal",
        "unlimited",
        "saog",
        "saoc",
        "aj",
        "yoaj",
        "oaj",
        "akc. spol.",
        "a.s.",
        "akciová společnost",
        "aktiengesellschaft",
    ],
    "Joint Venture": ["esv", "gie", "kv.", "qk"],
    "Limited": [
        "pty. ltd.",
        "pty ltd",
        "ltd",
        "l.t.d.",
        "bvba",
        "d.o.o.",
        "ltda",
        "gmbh",
        "g.m.b.h",
        "gesellschaft mit beschränkter haftung",
        "kft.",
        "kht.",
        "zrt.",
        "ehf.",
        "s.a.r.l.",
        "d.o.o.e.l.",
        "s. de r.l.",
        "s. de r.l. de c.v.",
        "b.v.",
        "tapui",
        "sp. z.o.o.",
        "sp. z o.o.",
        "spółka z o.o.",
        "spółka z ograniczoną odpowiedzialnością",
        "s.r.l.",
        "s.l.",
        "s.l.n.e.",
        "ood",
        "oy",
        "rt.",
        "teo",
        "uab",
        "scs",
        "sprl",
        "limited",
        "bhd.",
        "sdn. bhd.",
        "sdn bhd",
        "as",
        "lda.",
        "tov",
        "pp",
        "товариство з обмеженою відповідальністю",
        "tovarystvo z obmezhenoiu vidpovidalnistiu",
    ],
    "Limited Liability Company": [
        "pllc",
        "llc",
        "l.l.c.",
        "plc.",
        "plc",
        "hf.",
        "oyj",
        "a.e.",
        "nyrt.",
        "p.l.c.",
        "sh.a.",
        "s.a.",
        "s.r.l.",
        "srl.",
        "srl",
        "aat",
        "3at",
        "d.d.",
        "s.r.o.",
        "s. r. o.",
        "spol. s r.o.",
        "spol. s r. o.",
        "s.m.b.a.",
        "smba",
        "sarl",
        "nv",
        "sa",
        "aps",
        "a/s",
        "p/s",
        "sae",
        "sasu",
        "eurl",
        "ae",
        "cpt",
        "as",
        "ab",
        "asa",
        "ooo",
        "dat",
        "vat",
        "zat",
        "mchj",
        "a.d.",
        "společnost s ručením omezeným",
        "spoločnosť s ručením obmedzeným",
        "spol. s.r.o.",
        "sabiedrība ar ierobežotu atbildību",
        "приватне підприємство",
        "pryvatne pidpryyemstvo",
        "exploitation agricole à responsabilité limitée",
    ],
    "Limited Liability Company in Liquidation": [
        "spol. s r.o. v likvidaci",
        "spol. s.r.o. v likvidaci",
        "s.r.o. v likvidácii",
        "spol. s r.o. v likvidácii",
        "spol. s.r.o. v likvidácii",
        "s.r.o. v likvidácii",
        "spółka z ograniczoną odpowiedzialnością likwidacji",
    ],
    "Limited Liability Limited Partnership": ["lllp", "l.l.l.p."],
    "Limited Liability Partnership": [
        "llp",
        "l.l.p.",
        "sp.p.",
        "s.c.a.",
        "s.c.s.",
    ],
    "Limited Partnership": [
        "gmbh & co. kg",
        "gmbh & co. kg",
        "lp",
        "l.p.",
        "s.c.s.",
        "s.c.p.a",
        "comm.v",
        "k.d.",
        "k.d.a.",
        "s. en c.",
        "e.e.",
        "s.a.s.",
        "s. en c.",
        "c.v.",
        "s.k.a.",
        "sp.k.",
        "s.cra.",
        "ky",
        "scs",
        "kg",
        "kommanditgesellschaft",
        "kd",
        "k/s",
        "ee",
        "secs",
        "kda",
        "ks",
        "kb",
        "kt",
        "k.s.",
        "komanditní společnost",
        "spółka komandytowa",
        "komanditná spoločnosť",
    ],
    "Mutual Fund": ["sicav"],
    "No Liability": ["nl"],
    "Non-Profit": ["vzw", "ses.", "gte."],
    "Private Company": ["private", "pte", "xk"],
    "Professional Corporation": ["p.c.", "vof", "snc"],
    "Professional Limited Liability Company": ["pllc", "p.l.l.c."],
    "Sole Proprietorship": [
        "e.u.",
        "s.p.",
        "t:mi",
        "tmi",
        "e.v.",
        "e.c.",
        "et",
        "obrt",
        "fie",
        "ij",
        "fop",
        "xt",
    ],
}

terms_by_country = {
    "Albania": ["sh.a.", "sh.p.k."],
    "Argentina": [
        "s.a.",
        "s.r.l.",
        "s.c.p.a",
        "scpa",
        "s.c.e i.",
        "s.e.",
        "s.g.r",
        "soc.col.",
    ],
    "Australia": ["nl", "pty. ltd.", "pty ltd"],
    "Austria": ["e.u.", "stg", "gesbr", "a.g.", "ag", "og", "kg"],
    "Belarus": [
        "tavarystva z abmezhavanaj adkaznascyu",
        "zakrytae akcyyanernae tavarystva",
        "zat",
        "zao",
        "up",
        "taa",
        "rup",
        "oao",
        "aat",
        "aat",
        "3at",
        "чтуп",
        "сооо",
        "иооо",
        "чуп",
        "фпг",
        "тда",
        "таа",
        "руп",
        "ооо",
        "одо",
        "оао",
        "зат",
        "зао",
        "аат",
        "чп",
        "уп",
        "тк",
        "дп",
        "ва",
        "частное унитарное предприятие",
        "таварыства з абмежаванай адказнасцю",
        "таварыства з дадатковай адказнасцю",
        "адкрытае акцыянернае таварыства",
        "закрытае акцыянернае таварыства",
        "общество с ограниченной ответственностью",
        "общество с дополнительной ответственностью",
        "унітарнае прадпрыемства",
        "вытворчае аб'яднанне",
        "фінансово-промислова група",
        "канцэрн",
        "дачэрняя кампанія",
        "транснацыяльны канцэрн",
        "холдынг",
        "республиканское унитарное предприятие",
        "открытое акционерное общество",
        "закрытое акционерное общество",
        "иностранное общество с ограниченной ответственностью",
        "частное унитарное предприятие",
        "частное предприятие",
        "частное транспортное унитарное предприятие",
        "унитарное предприятие",
        "совместное общество с ограниченной ответственностью",
        "частное производственно торговое унитарное предприятие",
    ],
    "Belgium": [
        "esv",
        "vzw",
        "vof",
        "snc",
        "comm.v",
        "scs",
        "bvba",
        "sprl",
        "cvba",
        "cvoa",
        "sca",
        "sep",
        "gie",
    ],
    "Bosnia / Herzegovina": [
        "d.d.",
        "a.d.",
        "d.n.o.",
        "d.o.o.",
        "k.v.",
        "s.p.",
    ],
    "Brazil": [
        "ltda",
        "s.a.",
        "pllc",
        "ad",
        "adsitz",
        "ead",
        "et",
        "kd",
        "kda",
        "sd",
    ],
    "Bulgaria": [
        "ad",
        "adsitz",
        "ead",
        "et",
        "kd",
        "kda",
        "sd",
        "едноличен търговец",
        "ад",
        "aktsionerno drujestvo",
        "акционерно дружество",
        "adsits",
        "адсиц",
        "aktsionerno druzhestvo sus spetsialna investitsionna tsel",
        "акционерно дружество със специална инвестиционна цел",
        "еад",
        "ednolichno aktsionerno druzhestvo",
        "еднолично акционерно дружество",
        "eood",
        "еоод",
        "ednolichno druzhestvo s ogranichena otgovornost",
        "еднолично дружество с ограничена отговорност",
        "et",
        "ет",
        "ednolichen turgovetz",
        "едноличен търговец",
        "ood",
        "оод",
        "drujestvo s ogranichena otgovornost",
        "дружество с ограничена отговорност",
        "kd",
        "кд",
        "komanditno druzhestvo",
        "командитно дружество",
        "kda",
        "кда",
        "komanditno druzhestvo s aktzii",
        "командитно дружество с акции",
        "sd",
        "сд",
        "subiratelno druzhestvo",
        "събирателно дружество",
        "частное торговое унитарное предприятие",
    ],
    "Cambodia": ["gp", "sm pte ltd.", "pte ltd.", "plc ltd.", "peec", "sp"],
    "Canada": ["gp", "lp", "sp"],
    "Chile": [
        "eirl",
        "s.a.",
        "sgr",
        "s.g.r.",
        "ltda",
        "s.p.a.",
        "sa",
        "s. en c.",
        "ltda.",
    ],
    "China": [
        "有限公司",
        "yǒuxiàn gōngsī",
        "股份有限公司",
        "gǔfèn yǒuxiàn gōngsī)",
        "无限责任公司",
        "無限責任公司",
        "wúxiàn zérèn gōngsī",
        "有限责任股份公司",
        "有限責任股份公司",
        "股份公司",
        "yǒuxiàn zérèn gǔfèn gōngsī",
        "有限责任公司",
        "有限責任公司",
        "上市公司",
        "私人公司",
        "担保有限公司",
        "擔保有限公司",
        "有限公司",
        "有限合伙",
        "有限合夥",
        "有限责任",
        "集团公司",
        "公司集团",
        "集團公司",
        "公司集團",
    ],
    "Columbia": ["s.a.", "e.u.", "s.a.s.", "suc. de descendants", "sca"],
    "Croatia": ["d.d.", "d.o.o.", "obrt"],
    "Czech Republic": [
        "a.s.",
        "akc. spol.",
        "s.r.o.",
        "spol. s r.o.",
        "spol. s r. o.",
        "v.o.s.",
        "ve\xc5\x99. obch. spol.",
        "a spol.",
        "k.s.",
        "kom. spol.",
        "kom. spol.",
    ],
    "Denmark": [
        "i/s",
        "a/s",
        "k/s",
        "p/s",
        "amba",
        "a.m.b.a.",
        "fmba",
        "f.m.b.a.",
        "smba",
        "s.m.b.a.",
        "g/s",
    ],
    "Dominican Republic": [
        "c. por a.",
        "cxa",
        "s.a.",
        "s.a.s.",
        "srl.",
        "srl",
        "eirl.",
        "sa",
        "sas",
    ],
    "Ecuador": ["s.a.", "c.a.", "sa", "ep"],
    "Egypt": ["sae"],
    "Estonia": ["fie", "oü", "as"],
    "Finland": [
        "t:mi",
        "tmi",
        "as oy",
        "as.oy",
        "ay",
        "ky",
        "oy",
        "oyj",
        "ok",
    ],
    "France": [
        "sicav",
        "sarl",
        "sogepa",
        "ei",
        "eurl",
        "sasu",
        "fcp",
        "gie",
        "sep",
        "snc",
        "scs",
        "sca",
        "scop",
        "sem",
        "sas",
        "sci",
        "societe civile immobiliere",
    ],
    "Germany": [
        "gmbh & co. kg",
        "gmbh & co. kg",
        "e.g.",
        "e.v.",
        "gbr",
        "ohg",
        "partg",
        "kgaa",
        "gmbh",
        "g.m.b.h.",
        "egmbh",
        "eingetragene genossenschaft mit beschränkter haftpflicht",
        "ag",
        "kg",
        "kommanditgesellschaft",
        "aktiengesellschaft",
        "gesellschaft mit beschränkter haftung",
        "mbh & co. kg",
    ],
    "Greece": [
        "a.e.",
        "ae",
        "e.e.",
        "ee",
        "epe",
        "e.p.e.",
        "mepe",
        "m.e.p.e.",
        "o.e.",
        "oe",
        "ovee",
        "o.v.e.e.",
        "Anónimi Etaireía",
        "Ανώνυμη Εταιρεία",
        "Anónimi Viomichanikí Emborikí Etaireía",
        "Ανώνυμη Βιομηχανική Εμπορική Εταιρεία",
        "Eterórrithmi Etaireía",
        "Ετερόρρυθμη Εταιρία",
        "Etaireía Periorisménis Efthínis",
        "Εταιρεία Περιορισμένης Ευθύνης",
        "Ε.Π.Ε.",
        "Monoprósopi Etaireía Periorisménis Efthínis",
        "Μονοπρόσωπη Ε.Π.Ε.",
        "Μ.Ε.Π.Ε.",
        "Omórrithmi Etaireía",
        "Ομόρρυθμη Εταιρεία",
        "Ο.Ε.",
        "Omórrithmi Viomichanikí Emborikí Etaireía",
        "Ομόρρυθμη Βιομηχανική Εμπορική Εταιρεία",
        "Ο.Β.Ε.Ε.",
        "I.K.E.",
        "Idiotiki Kefalaiouchiki Etaireía",
        "Ιδιωτική Κεφαλαιουχική Εταιρεία",
        "atomikís epicheírisis",
        "ατομικής επιχείρησης",
    ],
    "Guatemala": ["s.a.", "sa"],
    "Haiti": ["sa"],
    "Hong Kong": ["ltd", "unltd", "ultd", "limited"],
    "Hungary": [
        "e.v.",
        "e.c.",
        "bt.",
        "kft.",
        "kht.",
        "kkt.",
        "k.v.",
        "zrt.",
        "nyrt",
        "ev",
        "ec",
        "rt.",
    ],
    "Iceland": ["ehf.", "hf.", "ohf.", "s.f.", "ses."],
    "India": ["pvt. ltd.", "ltd.", "psu", "pse"],
    "Indonesia": ["ud", "fa", "pt"],
    "Ireland": ["cpt", "teo"],
    "Israel": ["b.m.", "bm", "ltd", "limited"],
    "Italy": [
        "s.n.c.",
        "s.a.s.",
        "s.p.a.",
        "s.a.p.a.",
        "s.r.l.",
        "s.c.r.l.",
        "s.s.",
    ],
    "Japan": ["k.k.", "g.k.", "gk", "y.k."],
    "Latvia": ["as", "sia", "ik", "ps", "ks"],
    "Lebanon": ["sal"],
    "Lithuania": ["uab", "ab", "ij", "mb"],
    "Luxemborg": ["s.a.", "s.a.r.l.", "secs"],
    "Macedonia": ["d.o.o.", "d.o.o.e.l", "k.d.a.", "j.t.d.", "a.d.", "k.d."],
    "Malaysia": ["bhd.", "sdn. bhd.", "sdn bhd"],
    "Mexico": [
        "s.a.",
        "s. de. r.l.",
        "s. en c.",
        "s.a.b.",
        "s.a.p.i.",
        "s.a. de c.v.",
    ],
    "Moldova": ["societatea cu raspundere limitata"],
    "Mongolia": ["xk", "xxk"],
    "Montenegro": [
        "Preduzetnik",
        "O.D.",
        "Ortačko Društvo",
        "K.D.",
        "Komanditno Društvo",
        "A.D.",
        "Akcionarsko Društvo",
        "D.O.O.",
        "Društvo sa Ograničenom Odgovornošću",
    ],
    "Netherlands": [
        "v.o.f.",
        "c.v.",
        "b.v.",
        "n.v.",
        "stichting",
    ],
    "New Zealand": ["tapui", "ltd", "limited"],
    "Nigeria": ["gte.", "plc", "ltd.", "ultd."],
    "Norway": [
        "asa",
        "as",
        "ans",
        "ba",
        "bl",
        "da",
        "etat",
        "fkf",
        "hf",
        "iks",
        "kf",
        "ks",
        "nuf",
        "rhf",
        "sf",
    ],
    "Oman": ["saog", "saoc"],
    "Pakistan": ["ltd.", "pvt. ltd.", "ltd", "limited"],
    "Peru": ["sa", "s.a.", "s.a.a."],
    "Philippines": [
        "coop.",
        "corp.",
        "corp",
        "ent.",
        "inc.",
        "inc",
        "llc",
        "l.l.c.",
        "ltd.",
    ],
    "Poland": [
        "p.p.",
        "s.k.a.",
        "sp.j.",
        "sp.k.",
        "sp.p.",
        "sp. z.o.o.",
        "s.c.",
        "s.a.",
        "spółka z ograniczoną odpowiedzialnością",
    ],
    "Portugal": ["lda.", "crl", "s.a.", "s.f.", "sgps"],
    "Romania": [
        "societăți de persoane",
        "societatea în nume colectiv",
        "societatea în comandită simplă",
        "societatea în comandită pe acțiuni",
        "societatea pe acțiuni",
        "societate cu răspundere limitată",
        "societatea cu răspundere limitată cu proprietar unic",
        "srl cu proprietar unic",
        "s.a.",
        "s.c.a.",
        "s.c.s.",
        "s.n.c.",
        "s.r.l.",
        "pfa",
        "persoana fizica autorizata",
        "o.n.g.",
        "organizație non-guvernamentală",
        "întreprindere individuală",
        "întreprinderea individuală",
    ],
    "Russia": [
        "zakrytoe akcionernoe obshhestvo",
        "akcionernoe obshhestvo",
        "gruppa kompanij",
        "zao",
        "pao",
        "kao",
        "gk",
        "fkp",
        "fgup",
        "ao",
        "ooo",
        "oao",
        "zao",
        "3ao",
        "пао",
        "оао",
        "ооо",
        "оинно",
        "фгуп",
        "фгку",
        "фгбу",
        "фгау",
        "гупс",
        "фкп",
        "спк",
        "ран",
        "ппк",
        "пао",
        "ооо",
        "оао",
        "нпф",
        "нмо",
        "муп",
        "ммо",
        "мку",
        "мкп",
        "мбу",
        "мау",
        "зао",
        "гку",
        "гбу",
        "гау",
        "ган",
        "ано",
        "эф",
        "чу",
        "хт",
        "хп",
        "хо",
        "хк",
        "фх",
        "уп",
        "са",
        "ро",
        "ра",
        "пт",
        "пк",
        "оф",
        "оу",
        "кх",
        "кп",
        "ип",
        "гк",
        "бф",
        "ао",
        "унитарное предприятие",
        "казенное предприятие",
        "федеральное казенное предприятие",
        "муниципальное казенное предприятие",
        "федеральное государственное унитарное предприятие",
        "государственное унитарное предприятие",
        "муниципальное унитарное предприятие",
        "фонд",
        "благотворительный фонд",
        "негосударственный пенсионный фонд",
        "общественный фонд",
        "экологический фонд",
        "автономная некоммерческая организация",
        "религиозная организация",
        "публично-правовая компания",
        "государственная корпорация",
        "государственная компания",
        "отделение иностранной некоммерческой неправительственной организации",
        "учреждение",
        "федеральное государственное автономное учреждение",
        "федеральное государственное бюджетное учреждение",
        "федеральное государственное казенное учреждение",
        "государственное автономное учреждение",
        "государственное бюджетное учреждение",
        "государственное казенное учреждение",
        "государственная академия наук",
        "российская академия наук",
        "муниципальное автономное учреждение",
        "муниципальное бюджетное учреждение",
        "муниципальное казенное учреждение",
        "частное учреждение",
        "благотворительное учреждение",
        "общественное учреждение",
        "межправительственная международная организация",
        "неправительственная международная организация",
        "крестьянское хозяйство",
        "фермерское хозяйство",
        "хозяйственное партнерство",
        "производственный кооператив",
        "артель",
        "сельскохозяйственный производственный кооператив",
        "сельскохозяйственная артель",
        "колхоз",
        "рыболовецкая артель",
        "кооперативное хозяйство",
        "коопхоз",
        "хозяйственное товарищество",
        "полное товарищество",
        "товарищество на вере",
        "коммандитное товарищество",
        "хозяйственное общество",
        "акционерное общество",
        "открытое акционерное общество",
        "закрытое акционерное общество",
        "публичное акционерное общество",
        "общество с ограниченной ответственностью",
        "индивидуальный предприниматель",
        "группа компаний",
        "холдинговая компания",
        "интегрированная структура",
    ],
    "Serbia": ["d.o.o.", "a.d.", "k.d.", "o.d."],
    "Singapore": [
        "bhd",
        "pte ltd",
        "sdn bhd",
        "llp",
        "l.l.p.",
        "ltd.",
        "pte",
        "pte. ltd.",
    ],
    "Slovenia": ["d.d.", "d.o.o.", "d.n.o.", "k.d.", "s.p."],
    "Slovakia": [
        "a.s.",
        "akc. spol.",
        "s.r.o.",
        "spol. s r.o.",
        "spol. s r. o.",
        "k.s.",
        "kom. spol.",
        "v.o.s.",
        "a spol.",
    ],
    "Spain": [
        "s.a.",
        "s.a.d.",
        "s.l.",
        "s.l.l.",
        "s.l.n.e.",
        "s.c.",
        "s.cra",
        "s.coop",
        "sal",
        "sccl",
    ],
    "Sweden": ["ab", "hb", "kb"],
    "Switzerland": ["ab", "sa", "gmbh", "g.m.b.h.", "sarl", "sagl"],
    "Turkey": ["koop."],
    "Ukraine": [
        "tov",
        "sp",
        "pzii",
        "prat",
        "pp",
        "pat",
        "mpp",
        "ip",
        "dochp",
        "dp",
        "at",
        "dat",
        "fop",
        "kt",
        "pt",
        "tdv",
        "tov",
        "pp",
        "vat",
        "zat",
        "at",
        "вкксу",
        "пзіі",
        "тзов",
        "прат",
        "осбб",
        "дочп",
        "зіі",
        "фоп",
        "тов",
        "тдв",
        "сст",
        "спд",
        "сок",
        "свк",
        "пфо",
        "пск",
        "пог",
        "пат",
        "піі",
        "осс",
        "осн",
        "оог",
        "омс",
        "одв",
        "оас",
        "нпф",
        "мпп",
        "зат",
        "жбк",
        "даз",
        "ват",
        "сп у формі тов",
        "хк",
        "фг",
        "фб",
        "тс",
        "тб",
        "ст",
        "сс",
        "сп",
        "ск",
        "ро",
        "пт",
        "пп",
        "по",
        "ор",
        "оп",
        "оо",
        "ок",
        "кт",
        "кс",
        "кп",
        "ко",
        "кб",
        "дп",
        "до",
        "гс",
        "го",
        "гк",
        "вк",
        "бо",
        "ат",
        "ао",
        "аб",
        "іп",
        "дат",
        "державне акціонерне товариство",
        "derzhavne aktsionerne tovarystvo",
        "фоп",
        "фізична особа підприємець",
        "fizychna osoba pidpryyemets",
        "кт",
        "командитне товариство",
        "komandytne tovarystvo",
        "пt",
        "повне товариство",
        "povne tovarystvo",
        "тдв",
        "tob",
        "пп",
        "приватне підприємство",
        "pryvatne pidpryyemstvo",
        "ват",
        "вiдкрите акцiонерне товариство",
        "vidkryte aktsionerne tovarystvo",
        "пат",
        "публічне акціонерне товариство",
        "publichne aktsionerne tovarystvo",
        "зат",
        "закрите акцiонерне товариство",
        "zakryte aktsionerne tovarystvo",
        "прат",
        "приватне акціонерне товариство",
        "prytvatne aktsionerne tovarystvo",
        "ат",
        "акціонерне товариство",
        "aktsionerne tovarystvo",
        "релігійна організація",
        "громадська організація",
    ],
    "United Kingdom": [
        "plc.",
        "plc",
        "cic",
        "cio",
        "l.l.p.",
        "llp",
        "l.p.",
        "lp",
        "ltd.",
        "ltd",
        "limited",
    ],
    "United States of America": [
        "llc",
        "inc.",
        "corporation",
        "incorporated",
        "company",
        "limited",
        "corp.",
        "inc.",
        "inc",
        "llp",
        "l.l.p.",
        "pllc",
        "and company",
        "& company",
        "inc",
        "inc.",
        "corp.",
        "corp",
        "ltd.",
        "ltd",
        "& co.",
        "& co",
        "co.",
        "co",
        "lp",
    ],
    "Uzbekistan": [
        "mchj",
        "qmj",
        "aj",
        "oaj",
        "yoaj",
        "xk",
        "xt",
        "ok",
        "uk",
        "qk",
    ],
}
